// Mock API data - In production, replace with Axios calls to real API
// src/api/mockApi.js (updated fetchIPOs)
export const fetchIPOs = async () => {
  return [
    {
      id: 1,
      name: "Vidya Wires",
      fullName: "Vidya Wires Ltd",
      logo: "/images/vidya-logo.png",
      open: "03 Dec 2025",
      close: "05 Dec 2025",
      listing: "10 Dec 2025",
      price: "48-52",
      lot: 288,
      subscription: "26.16x",
      listingPrice: null,
      performance: null,
      type: "Mainboard",
      status: "live",
    },
    {
      id: 2,
      name: "Aequs Limited",
      fullName: "Aequs Aerospace",
      logo: "/images/aequs.png",
      open: "03 Dec 2025",
      close: "05 Dec 2025",
      listing: "10 Dec 2025",
      price: "118-124",
      lot: 120,
      subscription: "101.01x",
      listingPrice: null,
      performance: null,
      type: "Mainboard",
      status: "live",
    },
    {
      id: 3,
      name: "Meesho Limited",
      fullName: "Meesho (Social Commerce)",
      logo: "/images/meesho.jpg",
      open: "03 Dec 2025",
      close: "05 Dec 2025",
      listing: "10 Dec 2025",
      price: "105-111",
      lot: 135,
      subscription: "78.88x",
      listingPrice: null,
      performance: null,
      type: "Mainboard",
      status: "live",
    },
    {
      id: 4,
      name: "Sudeep Pharma",
      fullName: "Sudeep Pharma Pvt Ltd",
      open: "21 Nov 2025",
      close: "25 Nov 2025",
      listing: "28 Nov 2025",
      price: "593",
      lot: 25,
      subscription: "93.32x",
      listingPrice: "730",
      performance: "+23.10%",
      type: "Mainboard",
    },
    {
      id: 5,
      name: "Excelsoft Technologies",
      open: "19 Nov 2025",
      close: "21 Nov 2025",
      listing: "26 Nov 2025",
      price: "120",
      lot: 100,
      subscription: "42.83x",
      listingPrice: "135",
      performance: "+12.50%",
      type: "Mainboard",
    },
    {
      id: 6,
      name: "Capillary Technologies",
      open: "14 Nov 2025",
      close: "18 Nov 2025",
      listing: "21 Nov 2025",
      price: "577",
      lot: 25,
      subscription: "51.75x",
      listingPrice: "571.90",
      performance: "-0.88%",
      type: "Mainboard",
    },
    {
      id: 7,
      name: "Ola Electric",
      fullName: "Ola Electric Mobility",
      open: "Upcoming",
      close: "TBA",
      listing: "TBA",
      price: "TBA",
      lot: null,
      subscription: null,
      listingPrice: null,
      performance: null,
      type: "Mainboard",
      status: "upcoming",
    },
    {
      id: 8,
      name: "Swiggy",
      fullName: "Swiggy (Bundl Technologies)",
      open: "Upcoming",
      close: "TBA",
      listing: "TBA",
      price: "TBA",
      lot: null,
      subscription: null,
      type: "Mainboard",
      status: "upcoming",
    },
    {
      id: 9,
      name: "Tata Capital",
      open: "Upcoming",
      close: "TBA",
      listing: "TBA",
      price: "TBA",
      type: "Mainboard",
      status: "upcoming",
    },
    {
      id: 10,
      name: "HDB Financial",
      fullName: "HDB Financial Services",
      open: "Upcoming",
      close: "TBA",
      listing: "TBA",
      price: "TBA",
      type: "Mainboard",
      status: "upcoming",
    },
    {
      id: 11,
      name: "Chemkart India",
      open: "10 Dec 2025",
      close: "12 Dec 2025",
      listing: "17 Dec 2025",
      price: "85-90",
      lot: 160,
      subscription: null,
      type: "SME",
      status: "upcoming",
    },
    {
      id: 12,
      name: "Valiant Laboratories",
      open: "Closed",
      close: "Closed",
      listing: "05 Oct 2025",
      price: "140",
      lot: 100,
      subscription: "29.76x",
      listingPrice: "421",
      performance: "+200.71%",
      type: "SME",
    },
    {
      id: 13,
      name: "Plaza Wires",
      open: "Closed",
      close: "Closed",
      listing: "12 Oct 2025",
      price: "54",
      lot: 200,
      subscription: "160x",
      listingPrice: "76",
      performance: "+40.74%",
      type: "SME",
    }
  ];
};

export const fetchUnlisted = async () => {
  return [
    { id: 1, logo: '/images/zeta-logo.png', name: 'Zeta Tech', price: 2250, lot: 100, change: '+12%', liquidity: 'Medium' },
    { id: 2, logo: '/images/bluefin-logo.png', name: 'BlueFin Payments', price: 825, lot: 50, change: '-4%', liquidity: 'Low' },
    { id: 3, logo: '/images/paypal-logo.png', name: 'PayPlus Fintech', price: 1320, lot: 120, change: '+8%', liquidity: 'High' },

  ]
}


export const fetchBrokers = async () => {
  return [
    { id: 1, logo: '/images/zerodha.png', name: 'Zerodha', rating: 4.5, brokerage: '₹20/order', equities: 'Free Delivery', futures: '₹20' },
    { id: 2, logo: '/images/sharemarket.png', name: 'Share.Market', rating: 4.2, brokerage: '₹15/order', equities: '₹0', futures: '₹15' },
    { id: 3, logo: '/images/firstock.png', name: 'Firstock', rating: 4.0, brokerage: '₹10/order', equities: 'Free', futures: '₹10' },
  ]
}

export const fetchBlogs = async () => {
  return [
    { id: 1, title: 'Upcoming IPO: XYZ Corp', content: 'Details on right issues...' },
    // Add more for rights, dividends, bonus, bonds, NFO, REITs, IPOs
  ]
}